### ISSUE TITLE
exp2.py error

### ISSUE THREAD

**Issue by shadowcrow** [shadowcrow/WM#2]
Traceback (most recent call last):
  File "F:\Dropbox\working memory\output\exp2.py", line 210, in <module>
    main()
  File "F:\Dropbox\working memory\output\exp2.py", line 208, in main
    trial(STOPTIME_LIST[i])
  File "F:\Dropbox\working memory\output\exp2.py", line 179, in trial
    squ = SquarePos(color, category, position_neg, position_pos)
  File "F:\Dropbox\working memory\output\exp2.py", line 11, in __init__
    self.position= position
NameError: global name 'position' is not defined

**Comment by shadowcrow** [comment]
SET POSITION TO GLOBA;
